apiVersion: v1
kind: Pod
metadata:
  labels:
    build-name: really-doesnt-matter
spec:
  containers:
    # Docker packaging container
    # Need the debug container to get busybox
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      imagePullPolicy: Always
      command:
        - /busybox/cat
      tty: true
      volumeMounts:
        - name: jenkins-docker-cfg
          mountPath: /kaniko/.docker

    # For running tests
    - name: python3
      image: python:3.7.5-alpine3.10
      imagePullPolicy: Always
      command:
        - cat
      tty: true
  
  # docker-credentials secret must be pre-installed
  volumes:
    - name: jenkins-docker-cfg
      secret:
        secretName: docker-credentials
        items:
        - key: .dockerconfigjson
          path: config.json


