pipeline {
  agent {
    kubernetes {
      slaveConnectTimeout 240000
      activeDeadlineSeconds 43200
      yamlFile 'jenkins/default-pod.yaml'
    }
  }
  stages {
    stage('Branch Info') {
      steps {
        script {
          env.SHORT_BRANCH_NAME=sh(returnStdout: true, script: "git rev-parse --abbrev-ref HEAD").trim()

          // Set the tag number (date-based)
          env.TAG_NUMBER = sh(returnStdout: true, script: 'date +"%Y%m%d%H%m%S"').trim()
        }
        echo "Printenv Output: "
        sh 'printenv | sort'
      }
    }
    stage('Test') {
      steps {
        container('python3') {
          dir('src') {
            sh 'pip3 install -r requirements.txt'
            sh 'python3 test_requestcounter.py'
          }
        }
      }
    }
    stage('Build Container') {
      when {
        expression {
          env.SHORT_BRANCH_NAME == 'deploy'
        }
      }
      steps {
        container('jnlp') {
          dir('src/build-info') {
            sh 'echo ${GIT_COMMIT} > build.commithash'
            sh 'echo ${SHORT_BRANCH_NAME} > build.branch'
            sh 'echo ${TAG_NUMBER} > build.tagnumber'
            sh 'md5sum ../requestcounter.py > build.md5'
            sh 'for i in *; do echo "${i} ========="; cat ${i}; echo; done'
          }
        }
        container('kaniko') {
          sh '/kaniko/executor -f `pwd`/Dockerfile -c `pwd` --destination=joekottke/requestcounter:buildtest-v${TAG_NUMBER} --destination=joekottke/requestcounter:buildtest-latest'
        }
      }
    }
  }
}
